[package]
name = "dusk-abi"
version = "0.2.0"
authors = ["Kristoffer Str√∂m <kristoffer@dusk.network>"]
edition = "2018"

[dependencies]
kelvin = { version = "0.12", optional = true }
dataview = { git = "https://github.com/dusk-network/dataview.git" }

[features]
default = ["std", "debug"]
debug = []
std = ["kelvin"]
