[package]
name = "genesis"
version = "0.1.0"
authors = ["Kristoffer Str√∂m <kristoffer@rymdkoloni.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
